project_id = "vqvluqwadoaerghwyohk"

[functions.discord-logger]
verify_jwt = false

[functions.purchase-webhook] 
verify_jwt = false

[functions.realtime-voice-chat]
verify_jwt = false

[functions.achievement-tracker]
verify_jwt = false

[functions.vote-manager]
verify_jwt = false

[functions.analytics-data]
verify_jwt = false

[functions.custom-signup]
verify_jwt = false

[functions.custom-login]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.validate-session]
verify_jwt = false

[functions.custom-logout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.package-manager]
verify_jwt = false

[functions.staff-analytics]
verify_jwt = false

[functions.enhanced-server-stats]
verify_jwt = false

[functions.financial-analytics]
verify_jwt = false

[functions.discord-stats]
verify_jwt = false

[functions.data-seeder]
verify_jwt = false

[functions.kill-switch]
verify_jwt = false

[functions.fetch-individual-server-stats]
verify_jwt = false

[functions.update-all-server-stats]
verify_jwt = false